// Gym Tracker offline store, version 524d7e59f760. Generated by scripts/web.js – do not edit.
const CACHE = 'gym-tracker-524d7e59f760';
const FILES = ["_expo/static/js/web/index-055ca6c48831d2cb8a59d04a793194cc.js","apple-touch-icon-precomposed.png","apple-touch-icon.png","assets/assets/mascot/angry.a2f04d6451a378741aeeffd0bd372b79.png","assets/assets/mascot/cool.6d7f9a75622730625140f42a7563d1fb.png","assets/assets/mascot/effort.f85685068e6e30c53e1b2b5c52977083.png","assets/assets/mascot/fired.b7ec196461a0e7f937b8c66dd0bee710.png","assets/assets/mascot/laugh.c432b6e314c8060562d1d8fbec05f225.png","assets/assets/mascot/sad.87d0748cf9cd7d7ce69833decc755ecf.png","assets/assets/mascot/sleepy.498bb10b9de9e440c4204f89057c7197.png","assets/assets/mascot/smile.7d4a603b3d7bb29cd82e2e54df96c2c2.png","assets/assets/mascot/star.7709d58c650f8d191532d7fbf20cc7d2.png","assets/assets/mascot/wink.a138bba9115870a9a35e4ce7b48d820f.png","icons/apple-touch-icon.png","icons/favicon-32.png","icons/icon-192.png","icons/icon-512.png","index.html","manifest.json","privacy.html","support.html"];
const HASHED = /[.-][0-9a-f]{20,}\.\w+$/;
const OPTIONAL = /^assets\//;   // a photo that failed to download is fetched again the first time it is shown
const PAGES = FILES.filter((f) => /\.html$/.test(f) && f !== 'index.html').map((f) => new URL(f, self.registration.scope).pathname);

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await Promise.all(FILES.map(async (file) => {
      const url = new URL(file, self.registration.scope).href;
      try {
        const kept = HASHED.test(file) && (await caches.match(url));
        const res = kept || (await fetch(url, { cache: 'reload' }));
        if (!res.ok) throw new Error(file + ': ' + res.status);
        await cache.put(url, res);
      } catch (e) {
        if (!OPTIONAL.test(file)) throw e;
      }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith('gym-tracker-') && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || !req.url.startsWith(self.registration.scope)) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = req.mode === 'navigate' && !PAGES.includes(new URL(req.url).pathname)
      ? await cache.match(new URL('index.html', self.registration.scope).href)
      : await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    const res = await fetch(req);
    if (res.ok && req.mode !== 'navigate') cache.put(req, res.clone()).catch(() => {});
    return res;
  })());
});
