// Gym Tracker offline store, version 64e1a47db777. Generated by scripts/web.js – do not edit.
const CACHE = 'gym-tracker-64e1a47db777';
const FILES = ["_expo/static/js/web/index-f058902449a671a328e57d97ae30dbe5.js","apple-touch-icon-precomposed.png","apple-touch-icon.png","icons/apple-touch-icon.png","icons/favicon-32.png","icons/icon-192.png","icons/icon-512.png","index.html","manifest.json"];
const HASHED = /[.-][0-9a-f]{20,}\.\w+$/;
const OPTIONAL = /^assets\//;   // a photo that failed to download is fetched again the first time it is shown

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await Promise.all(FILES.map(async (file) => {
      const url = new URL(file, self.registration.scope).href;
      try {
        const kept = HASHED.test(file) && (await caches.match(url));
        const res = kept || (await fetch(url, { cache: 'reload' }));
        if (!res.ok) throw new Error(file + ': ' + res.status);
        await cache.put(url, res);
      } catch (e) {
        if (!OPTIONAL.test(file)) throw e;
      }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith('gym-tracker-') && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || !req.url.startsWith(self.registration.scope)) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = req.mode === 'navigate'
      ? await cache.match(new URL('index.html', self.registration.scope).href)
      : await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    const res = await fetch(req);
    if (res.ok && req.mode !== 'navigate') cache.put(req, res.clone()).catch(() => {});
    return res;
  })());
});
